name: Build Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile bot.py
          mkdir -p artifact
          cp dist/bot* artifact/
          cp config.example.yml artifact/

      - name: Compress artifact
        run: |
          cd artifact
          zip -r ../OneBotChatGPT.${{ matrix.os }}.${{ matrix.architecture }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OneBotChatGPT-${{ matrix.os }}-${{ matrix.architecture }}
          path: OneBotChatGPT.${{ matrix.os }}.${{ matrix.architecture }}.zip
