name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile bot.py
          mkdir -p artifact
          cp dist/bot* artifact/
          cp config.example.yml artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OneBotChatGPT.Linux.x64.zip
          path: artifact

  build-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile bot.py
          mkdir -p artifact
          cp dist/bot* artifact/
          cp config.example.yml artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OneBotChatGPT.Windows.x64
          path: artifact

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Compress subdirectories
        run: |
         for dir in */; do
           base=$(basename "$dir")
           zip -r "${base}.zip" "$dir"
          done 

      - name: Create release and upload artifacts
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: |
            OneBotChatGPT.Linux.x64.zip
            OneBotChatGPT.Windows.x64.zip
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
